---
apiVersion: v1
kind: Secret
metadata:
  name: appdev-quarkus-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-backstage/appdev-quarkus-gitops.git
